Repository leandroj1/ProyectoFinalPOO, pull requests merged in 2022-07, with the labels that each got.

#8 Tabla no editable para listados
  ProyectoFinal/src/customs/NonEditableTable.java
Labels: feature

#9 Utilidades y estado de las solicitudes
  ProyectoFinal/src/enums/EstadoSolicitud.java
  ProyectoFinal/src/logico/SolicitudEmpresa.java
  ProyectoFinal/src/logico/SolicitudPersonal.java
  ProyectoFinal/src/logico/Utils.java
Labels: feature

#10 Nuevo estado de solicitud añadida y refactorización
  ProyectoFinal/src/enums/EstadoSolicitud.java
  ProyectoFinal/src/enums/EstadoSolicitudEmpresa.java
  ProyectoFinal/src/enums/EstadoSolicitudPersonal.java
  ProyectoFinal/src/logico/SolicitudEmpresa.java
  ProyectoFinal/src/logico/SolicitudPersonal.java
Labels: feature

#11 Adding missing props to Bolsa Trabajo and Empresa
  ProyectoFinal/src/logico/BolsaTrabajo.java
  ProyectoFinal/src/logico/Empresa.java
  ProyectoFinal/src/logico/SolicitudEmpresa.java
  ProyectoFinal/src/logico/SolicitudPersonal.java
Labels: feature

#12 Visual ventanas
  ProyectoFinal/.classpath
  ProyectoFinal/.gitignore
  ProyectoFinal/src/dependencias/jcalendar-1.4.jar
  ProyectoFinal/src/dependencias/jgoodies-common-1.2.0.jar
  ProyectoFinal/src/dependencias/jgoodies-looks-2.4.1.jar
  ProyectoFinal/src/dependencias/junit-4.6.jar
  ProyectoFinal/src/visual/RegEmpresa.java
  ProyectoFinal/src/visual/RegPersonal.java
  ProyectoFinal/src/visual/RegSolEmpresa.java
  ProyectoFinal/src/visual/RegSolPersonal.java
Labels: feature

#13 Adding location prop for more acurated process of request-to-personal match
  ProyectoFinal/src/logico/Empresa.java
  ProyectoFinal/src/logico/Obrero.java
  ProyectoFinal/src/logico/Personal.java
  ProyectoFinal/src/logico/Tecnico.java
  ProyectoFinal/src/logico/Ubicacion.java
  ProyectoFinal/src/logico/Universitario.java
Labels: feature

#14 Agregando propiedades esenciales de Empresa
  ProyectoFinal/src/logico/Empresa.java
Labels: feature

#15 Cambios sugeridos por el profe
  ProyectoFinal/src/logico/Empresa.java
  ProyectoFinal/src/logico/Obrero.java
  ProyectoFinal/src/logico/Personal.java
  ProyectoFinal/src/logico/SolicitudEmpresa.java
  ProyectoFinal/src/logico/SolicitudPersonal.java
  ProyectoFinal/src/logico/Tecnico.java
  ProyectoFinal/src/logico/Universitario.java
Labels: feature

#17 Listado de empresas y de sus solicitudes
  ProyectoFinal/src/logico/Empresa.java
  ProyectoFinal/src/visual/ListadoSolicitudesEmpresa.java
  ProyectoFinal/src/visual/ListarEmpresas.java
Labels: feature, interfaz

#18 Porcentaje de match de la solicitud
  ProyectoFinal/src/logico/SolicitudEmpresa.java
Labels: cambios sugeridos, algoritmo de selección

#19 Interfaz de solicitud de empresa arreglada y nuevas utils
  ProyectoFinal/src/logico/Utils.java
  ProyectoFinal/src/visual/RegSolEmpresa.java
Labels: feature, interfaz, utils

#20 Cambios necesarios en SolicitudEmpresa
  ProyectoFinal/src/logico/SolicitudEmpresa.java
Labels: feature

#23 Agregando campo faltante en SolicitudEmpresa
  ProyectoFinal/src/logico/BolsaTrabajo.java
  ProyectoFinal/src/logico/SolicitudEmpresa.java
Labels: feature

#22 Util para validar emails
  ProyectoFinal/src/logico/Utils.java
Labels: feature, utils

#21 Agregando campos faltantes al Registro de empresa
  ProyectoFinal/src/logico/Empresa.java
  ProyectoFinal/src/visual/RegEmpresa.java
Labels: feature, interfaz

#24 Métodos útiles para contratar personal y anular solicitud de empresa
  ProyectoFinal/src/logico/BolsaTrabajo.java
Labels: feature

#25 UI solicitudes empresa
  ProyectoFinal/src/logico/Obrero.java
  ProyectoFinal/src/logico/SolicitudEmpresa.java
  ProyectoFinal/src/logico/Tecnico.java
  ProyectoFinal/src/logico/Universitario.java
  ProyectoFinal/src/logico/Utils.java
  ProyectoFinal/src/visual/ListadoSolicitudesEmpresa.java
  ProyectoFinal/src/visual/RegSolEmpresa.java
Labels: feature, interfaz, cambios sugeridos, utils
