Repository leandroj1/ProyectoFinalPOO, pull requests merged in 2022-08, with the labels that each got.

#27 Empresa
  ProyectoFinal/src/logico/Ubicacion.java
  ProyectoFinal/src/visual/ListarEmpresas.java
  ProyectoFinal/src/visual/Principal.java
  ProyectoFinal/src/visual/RegEmpresa.java
Labels: feature, interfaz

#28 Cambios en el listado de solicitudes de empresa y su creación
  ProyectoFinal/src/visual/ListadoSolicitudesEmpresa.java
  ProyectoFinal/src/visual/RegSolEmpresa.java
Labels: interfaz

#29 Feature/adding functionality to personal screens
  .DS_Store
  ProyectoFinal/src/logico/BolsaTrabajo.java
  ProyectoFinal/src/logico/Obrero.java
  ProyectoFinal/src/logico/Personal.java
  ProyectoFinal/src/logico/Tecnico.java
  ProyectoFinal/src/logico/Universitario.java
  ProyectoFinal/src/logico/Utils.java
  ProyectoFinal/src/visual/Principal.java
  ProyectoFinal/src/visual/RegPersonal.java
  ProyectoFinal/src/visual/RegSolPersonal.java
Labels: feature, interfaz

#31 Cambios lógicos en las interfaces
  ProyectoFinal/src/logico/Personal.java
  ProyectoFinal/src/logico/SolicitudPersonal.java
  ProyectoFinal/src/logico/Utils.java
  ProyectoFinal/src/visual/RegEmpresa.java
  ProyectoFinal/src/visual/RegPersonal.java
  ProyectoFinal/src/visual/RegSolPersonal.java
Labels: interfaz

#30 Algoritmo de selección
  ProyectoFinal/.classpath
  ProyectoFinal/img/check.png
  ProyectoFinal/img/error.png
  ProyectoFinal/img/not.png
  ProyectoFinal/src/customs/CheckBoxsEditableTable.java
  ProyectoFinal/src/logico/BolsaTrabajo.java
  ProyectoFinal/src/logico/Personal.java
  ProyectoFinal/src/logico/SolicitudEmpresa.java
  ProyectoFinal/src/logico/SolicitudPersonal.java
  ProyectoFinal/src/visual/ListadoSolicitudesEmpresa.java
  ProyectoFinal/src/visual/ManejoDeCandidatos.java
  ProyectoFinal/src/visual/PropiedadesCumplidasPersonal.java
  ProyectoFinal/src/visual/RegSolEmpresa.java
Labels: feature, interfaz, algoritmo de selección

#32 Fix agregarSolicitudEmpleado logic preventing to add it on the wrong case
  ProyectoFinal/src/logico/BolsaTrabajo.java
  ProyectoFinal/src/visual/RegSolPersonal.java
Labels: bug

#33 Arreglos lógicos en la UI
  ProyectoFinal/src/logico/SolicitudPersonal.java
  ProyectoFinal/src/logico/Utils.java
  ProyectoFinal/src/visual/ManejoDeCandidatos.java
  ProyectoFinal/src/visual/PropiedadesCumplidasPersonal.java
  ProyectoFinal/src/visual/RegEmpresa.java
  ProyectoFinal/src/visual/RegPersonal.java
  ProyectoFinal/src/visual/RegSolEmpresa.java
  ProyectoFinal/src/visual/RegSolPersonal.java
Labels: bug, interfaz

#34 Reportes
  ProyectoFinal/src/logico/BolsaTrabajo.java
  ProyectoFinal/src/visual/ListarEmpresas.java
  ProyectoFinal/src/visual/Principal.java
  ProyectoFinal/src/visual/RegEmpresa.java
  ProyectoFinal/src/visual/Reporte1.java
  ProyectoFinal/src/visual/Reporte2.java
  ProyectoFinal/src/visual/Reporte3.java
Labels: feature, interfaz

#35 Ficheros
  .gitignore
  ProyectoFinal/src/ficheros/UtilsFicheros.java
  ProyectoFinal/src/logico/BolsaTrabajo.java
  ProyectoFinal/src/logico/Empresa.java
  ProyectoFinal/src/logico/Obrero.java
  ProyectoFinal/src/logico/Personal.java
  ProyectoFinal/src/logico/SolicitudEmpresa.java
  ProyectoFinal/src/logico/SolicitudPersonal.java
  ProyectoFinal/src/logico/Tecnico.java
  ProyectoFinal/src/logico/Ubicacion.java
  ProyectoFinal/src/logico/Universitario.java
  ProyectoFinal/src/visual/ListadoSolicitudesEmpresa.java
  ProyectoFinal/src/visual/ListarEmpresas.java
  ProyectoFinal/src/visual/ManejoDeCandidatos.java
  ProyectoFinal/src/visual/Principal.java
  ProyectoFinal/src/visual/PropiedadesCumplidasPersonal.java
  ProyectoFinal/src/visual/RegEmpresa.java
  ProyectoFinal/src/visual/RegPersonal.java
  ProyectoFinal/src/visual/RegSolEmpresa.java
  ProyectoFinal/src/visual/RegSolPersonal.java
  ProyectoFinal/src/visual/Reporte1.java
  ProyectoFinal/src/visual/Reporte2.java
  ProyectoFinal/src/visual/Reporte3.java
Labels: feature

#37 Feature/loggin
  ProyectoFinal/src/logico/BolsaTrabajo.java
  ProyectoFinal/src/logico/Main.java
  ProyectoFinal/src/logico/Usuario.java
  ProyectoFinal/src/visual/AgregarUsuario.java
  ProyectoFinal/src/visual/CambiarContrasegna.java
  ProyectoFinal/src/visual/ListadoSolicitudesEmpresa.java
  ProyectoFinal/src/visual/ListarEmpresas.java
  ProyectoFinal/src/visual/ListarUsuarios.java
  ProyectoFinal/src/visual/Login.java
  ProyectoFinal/src/visual/ManejoDeCandidatos.java
  ProyectoFinal/src/visual/Principal.java
  ProyectoFinal/src/visual/PropiedadesCumplidasPersonal.java
  ProyectoFinal/src/visual/RegEmpresa.java
  ProyectoFinal/src/visual/RegPersonal.java
  ProyectoFinal/src/visual/RegSolEmpresa.java
  ProyectoFinal/src/visual/RegSolPersonal.java
  ProyectoFinal/src/visual/Reporte1.java
  ProyectoFinal/src/visual/Reporte2.java
  ProyectoFinal/src/visual/Reporte3.java
Labels: feature

#38 Cosas que faltaban en manejo de candidatos
  ProyectoFinal/src/visual/ListadoSolicitudesEmpresa.java
  ProyectoFinal/src/visual/ManejoDeCandidatos.java
  ProyectoFinal/src/visual/Principal.java
  ProyectoFinal/src/visual/PropiedadesCumplidasPersonal.java
  ProyectoFinal/src/visual/RegEmpresa.java
  ProyectoFinal/src/visual/VerDescripcion.java
Labels: interfaz

#36 Feature/listado peronal y solicitud
  ProyectoFinal/src/logico/BolsaTrabajo.java
  ProyectoFinal/src/logico/Main.java
  ProyectoFinal/src/logico/Obrero.java
  ProyectoFinal/src/logico/Personal.java
  ProyectoFinal/src/logico/SolicitudPersonal.java
  ProyectoFinal/src/logico/Utils.java
  ProyectoFinal/src/visual/ListadoSolicitudesPersonal.java
  ProyectoFinal/src/visual/ListarPersonal.java
  ProyectoFinal/src/visual/Principal.java
  ProyectoFinal/src/visual/RegPersonal.java
  ProyectoFinal/src/visual/RegSolPersonal.java
Labels: feature
